version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "tesla-bot-oshada"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1hydriox1c5db"
s3_prefix = "tesla-bot-oshada"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = ["SentimentFunction=593765016513.dkr.ecr.us-east-1.amazonaws.com/teslabotoshada245705ac/sentimentfunction35d37012repo"]
